//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenseNet.Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SenseNet.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop and re-create database. If you uncheck this checkbox, we will still clear and recreate tables in the database, but will not drop the db itself..
        /// </summary>
        public static string DatabasePage_Choice_RecreateDb {
            get {
                return ResourceManager.GetString("DatabasePage_Choice_RecreateDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a connection to the database server..
        /// </summary>
        public static string DatabasePage_Details {
            get {
                return ResourceManager.GetString("DatabasePage_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        public static string DatabasePage_FormLabel_DatabaseName {
            get {
                return ResourceManager.GetString("DatabasePage_FormLabel_DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server.
        /// </summary>
        public static string DatabasePage_FormLabel_ServerName {
            get {
                return ResourceManager.GetString("DatabasePage_FormLabel_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database already exists. Please decide what should we do with it..
        /// </summary>
        public static string DatabasePage_Message_DbAlreadyExists {
            get {
                return ResourceManager.GetString("DatabasePage_Message_DbAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when connecting to the database server. Please make sure that you provided the correct names and you have enough permissions..
        /// </summary>
        public static string DatabasePage_Message_Error_DbConnection {
            get {
                return ResourceManager.GetString("DatabasePage_Message_Error_DbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string DatabasePage_Title {
            get {
                return ResourceManager.GetString("DatabasePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all the values..
        /// </summary>
        public static string Form_Validation_FillAllValues {
            get {
                return ResourceManager.GetString("Form_Validation_FillAllValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log folder.
        /// </summary>
        public static string InstallPage_Link_OpenLogFolder {
            get {
                return ResourceManager.GetString("InstallPage_Link_OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Sense/Net ECM.
        /// </summary>
        public static string InstallPage_Title {
            get {
                return ResourceManager.GetString("InstallPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying package....
        /// </summary>
        public static string InstallStatus_CopyingPackage {
            get {
                return ResourceManager.GetString("InstallStatus_CopyingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating website....
        /// </summary>
        public static string InstallStatus_CreatingWebSite {
            get {
                return ResourceManager.GetString("InstallStatus_CreatingWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing package....
        /// </summary>
        public static string InstallStatus_ExecutingPackage {
            get {
                return ResourceManager.GetString("InstallStatus_ExecutingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install finished, you may visit the new site or open the log file for details..
        /// </summary>
        public static string InstallStatus_Finished {
            get {
                return ResourceManager.GetString("InstallStatus_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install finished with error..
        /// </summary>
        public static string InstallStatus_Finished_Error_BeforeSnAdmin {
            get {
                return ResourceManager.GetString("InstallStatus_Finished_Error_BeforeSnAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install finished with error, please check the log file for details..
        /// </summary>
        public static string InstallStatus_Finished_Error_DuringSnAdmin {
            get {
                return ResourceManager.GetString("InstallStatus_Finished_Error_DuringSnAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing web folder....
        /// </summary>
        public static string InstallStatus_PreparingWebfolder {
            get {
                return ResourceManager.GetString("InstallStatus_PreparingWebfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparations completed, hit the Install button when ready..
        /// </summary>
        public static string InstallStatus_ReadyToGo {
            get {
                return ResourceManager.GetString("InstallStatus_ReadyToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the package you want to install..
        /// </summary>
        public static string PackagePage_Details {
            get {
                return ResourceManager.GetString("PackagePage_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package path.
        /// </summary>
        public static string PackagePage_FormLabel_PackagePath {
            get {
                return ResourceManager.GetString("PackagePage_FormLabel_PackagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a valid package..
        /// </summary>
        public static string PackagePage_Message_InvalidPackageFile {
            get {
                return ResourceManager.GetString("PackagePage_Message_InvalidPackageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package files (*.zip).
        /// </summary>
        public static string PackagePage_OpenFile_FilterText {
            get {
                return ResourceManager.GetString("PackagePage_OpenFile_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string PackagePage_Title {
            get {
                return ResourceManager.GetString("PackagePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a website where you want to install the package..
        /// </summary>
        public static string SelectWebsitePage_Details {
            get {
                return ResourceManager.GetString("SelectWebsitePage_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website folder:.
        /// </summary>
        public static string SelectWebsitePage_FormLabel_WebsitePath {
            get {
                return ResourceManager.GetString("SelectWebsitePage_FormLabel_WebsitePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an existing website..
        /// </summary>
        public static string SelectWebsitePage_Message_Error_SelectSite {
            get {
                return ResourceManager.GetString("SelectWebsitePage_Message_Error_SelectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select website.
        /// </summary>
        public static string SelectWebsitePage_Title {
            get {
                return ResourceManager.GetString("SelectWebsitePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add url to hosts file. This will let you access this custom url without DNS registration..
        /// </summary>
        public static string WebsitePage_AddToHosts_Description {
            get {
                return ResourceManager.GetString("WebsitePage_AddToHosts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the identity for the new website&apos;s application pool. The choosen account (in most cases a domain user) has to have access to the web folder and the database..
        /// </summary>
        public static string WebsitePage_AppPool_Description {
            get {
                return ResourceManager.GetString("WebsitePage_AppPool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a user with the correct password. It can be the currently logged in user (in the domain\username form). This can be changed later in IIS Manager..
        /// </summary>
        public static string WebsitePage_CustomIdentity_Description {
            get {
                return ResourceManager.GetString("WebsitePage_CustomIdentity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the details for the new IIS site..
        /// </summary>
        public static string WebsitePage_Details {
            get {
                return ResourceManager.GetString("WebsitePage_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App pool identity.
        /// </summary>
        public static string WebsitePage_FormLabel_AppPool {
            get {
                return ResourceManager.GetString("WebsitePage_FormLabel_AppPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string WebsitePage_FormLabel_Password {
            get {
                return ResourceManager.GetString("WebsitePage_FormLabel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website name.
        /// </summary>
        public static string WebsitePage_FormLabel_SiteName {
            get {
                return ResourceManager.GetString("WebsitePage_FormLabel_SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL (website binding).
        /// </summary>
        public static string WebsitePage_FormLabel_Url {
            get {
                return ResourceManager.GetString("WebsitePage_FormLabel_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (e.g. example.com or localhost:123).
        /// </summary>
        public static string WebsitePage_FormLabel_Url_Description {
            get {
                return ResourceManager.GetString("WebsitePage_FormLabel_Url_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string WebsitePage_FormLabel_Username {
            get {
                return ResourceManager.GetString("WebsitePage_FormLabel_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web folder path.
        /// </summary>
        public static string WebsitePage_FormLabel_WebfolderPath {
            get {
                return ResourceManager.GetString("WebsitePage_FormLabel_WebfolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an empty folder for the website..
        /// </summary>
        public static string WebsitePage_Message_DirectoryNotEmpty {
            get {
                return ResourceManager.GetString("WebsitePage_Message_DirectoryNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid web folder or you do not have enough permissions to create the directory..
        /// </summary>
        public static string WebsitePage_Message_Error_Webfolder {
            get {
                return ResourceManager.GetString("WebsitePage_Message_Error_Webfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to manage website..
        /// </summary>
        public static string WebsitePage_Message_Error_WebsiteAdmin {
            get {
                return ResourceManager.GetString("WebsitePage_Message_Error_WebsiteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid url..
        /// </summary>
        public static string WebsitePage_Message_IncorrectUrl {
            get {
                return ResourceManager.GetString("WebsitePage_Message_IncorrectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This url belongs to an existing website. Do you want to continue?.
        /// </summary>
        public static string WebsitePage_Message_WebsiteBindingExists {
            get {
                return ResourceManager.GetString("WebsitePage_Message_WebsiteBindingExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website already exists. Are you sure you want to use it?.
        /// </summary>
        public static string WebsitePage_Message_WebsiteExists {
            get {
                return ResourceManager.GetString("WebsitePage_Message_WebsiteExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS website.
        /// </summary>
        public static string WebsitePage_Title {
            get {
                return ResourceManager.GetString("WebsitePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose from the following options:.
        /// </summary>
        public static string WelcomePage_Details {
            get {
                return ResourceManager.GetString("WelcomePage_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Sense/Net ECM Installer.
        /// </summary>
        public static string WelcomePage_Title {
            get {
                return ResourceManager.GetString("WelcomePage_Title", resourceCulture);
            }
        }
    }
}
